[0m15:56:29.995207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C1DAA900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C4818690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C4818550>]}


============================== 15:56:30.030037 | 0276926b-1899-4b38-80e8-c144ce1fdc77 ==============================
[0m15:56:30.030037 [info ] [MainThread]: Running with dbt=1.8.8
[0m15:56:30.030962 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mayer Hedda\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init juti_utils', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:56:30.060173 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/Mayer Hedda/.dbt')}
[0m15:56:30.061035 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:56:30.063602 [debug] [MainThread]: Starter project path: C:\Users\Mayer Hedda\Documents\Tananyagok\dbt_env\Lib\site-packages\dbt\include\starter_project
[0m15:56:30.097886 [info ] [MainThread]: 
Your new dbt project "juti_utils" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:56:30.102133 [info ] [MainThread]: Setting up your profile.
[0m15:56:30.104575 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m15:56:30.107083 [debug] [MainThread]: Command `dbt init` failed at 15:56:30.106864 after 0.23 seconds
[0m15:56:30.107540 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C487BBB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C49CB410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C49C5480>]}
[0m15:56:30.107929 [debug] [MainThread]: Flushing usage events
[0m12:35:07.143673 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A265A2E660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2655DD810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2683A7ED0>]}


============================== 12:35:07.156446 | ca00f058-aebf-4860-8e79-e3d25c828f72 ==============================
[0m12:35:07.156446 [info ] [MainThread]: Running with dbt=1.8.8
[0m12:35:07.157869 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mayer Hedda\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m12:35:07.158609 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mayer Hedda\Documents\Tananyagok\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:35:07.159924 [debug] [MainThread]: Command `dbt deps` failed at 12:35:07.159780 after 0.20 seconds
[0m12:35:07.160310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2685AD6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A268461EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A268406580>]}
[0m12:35:07.160698 [debug] [MainThread]: Flushing usage events
